parameters:
  consumer_key: PUZMU8pKnHGEnRW3kynhQ
  consumer_secret: gFZLr6GpcakRxhzj6qWWjRqqAqVjBlEOxun6VRiXHo
  oauth_token: null
  oauth_token_secret: null
  fb_app_id: '190731834345740'
  fb_app_secret: ae3a926faaec553ac9b570eb78509e76
  fb_page_name: TestObjects
  fb_page_id: '190411274380147'
  fb_page_access_token: AAACteDc7yQwBAMGYgBfMIFVGzcZAFbWEGgSKtbqU8cU7n5nu00rEZBZCVmXKiEU56famVe5hJNWPHrTcCQdmN7ArmJZAZAswgQXcElfFsizz4Dxs3UqCu
  fb_user_id: '100000705769644'
  fb_access_token: AAACteDc7yQwBALQ2vbVK5LnI1XrZC2LZBgDujZCf1EAeOS9ENZCC7Jg63TNEGRXYrz3E7EhR1towIZB70r2D94rhSNsXnVd9izHdXJDEhRQZDZD
