google:
    resource: "@ObjectsAPIBundle/Resources/config/routing/google.yml"
    prefix:   /google

twitter_authentication:
    path:  /twitterauthentication/{popup}/{redirectRoute}
    defaults: { _controller: ObjectsAPIBundle:Twitter:index, popup: 'no' }

twitter_callback:
    path:  /twitter
    defaults: { _controller: ObjectsAPIBundle:Twitter:twitter }

save_twitter_tokens:
    path:  /twitter/save
    defaults: { _controller: ObjectsAPIBundle:Twitter:saveTwitterTokens }

twitt:
    path: /twitt/{status}
    defaults: { _controller: ObjectsAPIBundle:Twitter:twitt }

get_last_twitts:
    path: /twitts/{count}
    defaults: { _controller: ObjectsAPIBundle:Twitter:getLastTwitts }

facebook_button:
    path:  /facebookbutton/{facebookUserHandleRoute}/{permissions}/{cssClass}/{linkText}
    defaults: { _controller: ObjectsAPIBundle:Facebook:facebookButton }

facebook_app_id:
    path:  /facebook/app/id
    defaults: { _controller: ObjectsAPIBundle:Facebook:getFacbookApplicationId }

facebook_end_dailog:
    path:  /facebookenddialog
    defaults: { _controller: ObjectsAPIBundle:Facebook:endDialog }

facebook_one_user_handel:
    path:  /facebookoneuserhandel
    defaults: { _controller: ObjectsAPIBundle:Facebook:facebookOneUserHandeler }

linkedInButton:
    path:  /linkedInButton/{callbackUrl}/{popup}
    defaults: { _controller: ObjectsAPIBundle:Linkedin:linkedInButton, popup: 'no'}

linkedInCallBack:
    path:  /linkedInCallBack
    defaults: { _controller: ObjectsAPIBundle:Linkedin:linkedInCallBack}
